version: "3.9" 
# docker exec -it {CONTAINER_ID} sh
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - d:\\docker\\redis\\data:/data
      - d:\\docker\\redis\\redis.conf:/usr/local/etc/redis/redis.conf
      - d:\\docker\\redis\\logs:/logs/redis.log