version: "3.9" 
services:
  timescaledb:
    image: timescale/timescaledb:2.1.1-pg13
    container_name: timescaledb
    environment:
      POSTGRES_USER: timescaleuser
      POSTGRES_PASSWORD: timescaleuser
      POSTGRES_DB: timescale
    ports:
      - 5432:5432
    volumes:
      - /Users/chenhao/Documents/timescale/data:/var/lib/postgresql/data
