// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metricValue.proto

package data.platform.common.protobuf;

public interface MetricValueProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetricValueProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string metric = 1;</code>
   * @return The metric.
   */
  java.lang.String getMetric();
  /**
   * <code>string metric = 1;</code>
   * @return The bytes for metric.
   */
  com.google.protobuf.ByteString
      getMetricBytes();

  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>int64 eventTime = 3;</code>
   * @return The eventTime.
   */
  long getEventTime();

  /**
   * <code>double value = 4;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>int64 ttl = 5;</code>
   * @return The ttl.
   */
  long getTtl();
}
